version: '3.7'
services:
  app:
    build: .
    volumes:
      - .:/go/src
  db:
    build:
      context: .
      dockerfile: dockerfile
    image: github.com/desafio-cbt/transactiondb
    container_name: desafio-cbt-db
    restart: unless-stopped
    tty: true
    ports:
      - '25432:5432'
    environment:
      POSTGRES_DB: transactions
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data/desafio-cbt
    volumes:
      - desafio-cbt:/var/lib/postgresql/data

volumes:
    desafio-cbt: